services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        restart: unless-stopped
        depends_on:
            -   db
            -   redis
        volumes:
            -   .:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        volumes:
            -   .:/var/www
            -   ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        depends_on:
            -   backend
        networks:
            - app-network

    db:
        image: postgres:15-alpine
        container_name: db
        restart: unless-stopped
        environment:
            -   POSTGRES_DB=${DB_DATABASE}
            -   POSTGRES_USER=${DB_USERNAME}
            -   POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            -   postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
